import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Michal',
            email: 'admin@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Slim Shirt 1',
            category: 'Shirts',
            image: '/images/icade.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Slim Shirt 2',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 15,
            brand: 'Adidas',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Slim Shirt 3',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 90,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Slim Shirt 4',
            category: 'Shirts',
            image: '/images/p4.jpg',
            price: 80,
            countInStock: 30,
            brand: 'Puma',
            rating: 2.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Slim Shirt 5',
            category: 'Shirts',
            image: '/images/p5.jpg',
            price: 40,
            countInStock: 1,
            brand: 'Pierre One',
            rating: 3,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Slim Shirt 6',
            category: 'Shirts',
            image: '/images/p6.jpg',
            price: 15,
            countInStock: 0,
            brand: 'Zara',
            rating: 4,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};

export default data;